// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PalindromeRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PalindromeRequest) Reset()         { *m = PalindromeRequest{} }
func (m *PalindromeRequest) String() string { return proto.CompactTextString(m) }
func (*PalindromeRequest) ProtoMessage()    {}
func (*PalindromeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{0}
}

func (m *PalindromeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PalindromeRequest.Unmarshal(m, b)
}
func (m *PalindromeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PalindromeRequest.Marshal(b, m, deterministic)
}
func (m *PalindromeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PalindromeRequest.Merge(m, src)
}
func (m *PalindromeRequest) XXX_Size() int {
	return xxx_messageInfo_PalindromeRequest.Size(m)
}
func (m *PalindromeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PalindromeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PalindromeRequest proto.InternalMessageInfo

func (m *PalindromeRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type PalindromeResponse struct {
	IsPalindrome         bool     `protobuf:"varint,1,opt,name=isPalindrome,proto3" json:"isPalindrome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PalindromeResponse) Reset()         { *m = PalindromeResponse{} }
func (m *PalindromeResponse) String() string { return proto.CompactTextString(m) }
func (*PalindromeResponse) ProtoMessage()    {}
func (*PalindromeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{1}
}

func (m *PalindromeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PalindromeResponse.Unmarshal(m, b)
}
func (m *PalindromeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PalindromeResponse.Marshal(b, m, deterministic)
}
func (m *PalindromeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PalindromeResponse.Merge(m, src)
}
func (m *PalindromeResponse) XXX_Size() int {
	return xxx_messageInfo_PalindromeResponse.Size(m)
}
func (m *PalindromeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PalindromeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PalindromeResponse proto.InternalMessageInfo

func (m *PalindromeResponse) GetIsPalindrome() bool {
	if m != nil {
		return m.IsPalindrome
	}
	return false
}

type MathRequest struct {
	NumA                 float32  `protobuf:"fixed32,1,opt,name=NumA,proto3" json:"NumA,omitempty"`
	NumB                 float32  `protobuf:"fixed32,2,opt,name=NumB,proto3" json:"NumB,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MathRequest) Reset()         { *m = MathRequest{} }
func (m *MathRequest) String() string { return proto.CompactTextString(m) }
func (*MathRequest) ProtoMessage()    {}
func (*MathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{2}
}

func (m *MathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MathRequest.Unmarshal(m, b)
}
func (m *MathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MathRequest.Marshal(b, m, deterministic)
}
func (m *MathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MathRequest.Merge(m, src)
}
func (m *MathRequest) XXX_Size() int {
	return xxx_messageInfo_MathRequest.Size(m)
}
func (m *MathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MathRequest proto.InternalMessageInfo

func (m *MathRequest) GetNumA() float32 {
	if m != nil {
		return m.NumA
	}
	return 0
}

func (m *MathRequest) GetNumB() float32 {
	if m != nil {
		return m.NumB
	}
	return 0
}

type MathResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MathResponse) Reset()         { *m = MathResponse{} }
func (m *MathResponse) String() string { return proto.CompactTextString(m) }
func (*MathResponse) ProtoMessage()    {}
func (*MathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{3}
}

func (m *MathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MathResponse.Unmarshal(m, b)
}
func (m *MathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MathResponse.Marshal(b, m, deterministic)
}
func (m *MathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MathResponse.Merge(m, src)
}
func (m *MathResponse) XXX_Size() int {
	return xxx_messageInfo_MathResponse.Size(m)
}
func (m *MathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MathResponse proto.InternalMessageInfo

func (m *MathResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PalindromeRequest)(nil), "PalindromeRequest")
	proto.RegisterType((*PalindromeResponse)(nil), "PalindromeResponse")
	proto.RegisterType((*MathRequest)(nil), "MathRequest")
	proto.RegisterType((*MathResponse)(nil), "MathResponse")
}

func init() {
	proto.RegisterFile("math.proto", fileDescriptor_f139a3799a86a974)
}

var fileDescriptor_f139a3799a86a974 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdb, 0x2a, 0xa1, 0x8e, 0xf1, 0xe0, 0x0a, 0x52, 0x7a, 0x92, 0x45, 0xda, 0x7a, 0xc8,
	0x06, 0xfc, 0x83, 0xbd, 0x36, 0x78, 0xad, 0x48, 0x7a, 0xf3, 0x96, 0x3f, 0x4b, 0xb2, 0x98, 0xec,
	0xc6, 0xdd, 0xd9, 0xa8, 0x9f, 0xd9, 0x2f, 0x21, 0x6c, 0x83, 0x8d, 0xf4, 0x50, 0x6f, 0x33, 0x8f,
	0xdf, 0x7b, 0x03, 0xf3, 0x00, 0xea, 0x04, 0x4b, 0xd6, 0x68, 0x85, 0x8a, 0xce, 0xe1, 0xfc, 0x25,
	0xa9, 0x84, 0xcc, 0xb5, 0xaa, 0x79, 0xcc, 0xdf, 0x2d, 0x37, 0x48, 0x08, 0x1c, 0x7f, 0x28, 0x9d,
	0x4f, 0x86, 0x57, 0xc3, 0xc5, 0x49, 0xec, 0x66, 0xba, 0x04, 0xd2, 0x07, 0x4d, 0xa3, 0xa4, 0xe1,
	0x84, 0x82, 0x2f, 0xcc, 0x4e, 0x77, 0x8e, 0x71, 0xfc, 0x47, 0xa3, 0x0f, 0x70, 0xba, 0x4e, 0xb0,
	0xec, 0x85, 0x3f, 0xdb, 0x7a, 0xe5, 0xd0, 0x51, 0xec, 0xe6, 0x4e, 0x8b, 0x26, 0xa3, 0x5f, 0x2d,
	0xa2, 0x33, 0xf0, 0xb7, 0xb6, 0xee, 0xd4, 0x25, 0x78, 0x31, 0x37, 0xb6, 0xc2, 0xce, 0xd9, 0x6d,
	0xb7, 0xdf, 0xc3, 0x6d, 0xfe, 0x86, 0xeb, 0x56, 0x64, 0x9c, 0x5c, 0xc3, 0xd1, 0x2a, 0xcf, 0x89,
	0xcf, 0x7a, 0x47, 0xa7, 0x67, 0xac, 0x9f, 0x45, 0x07, 0xe4, 0x06, 0xc6, 0x1b, 0x9b, 0xa2, 0x4e,
	0x32, 0xfc, 0x07, 0xba, 0xb6, 0x15, 0x8a, 0xa6, 0xfa, 0x3a, 0x84, 0xce, 0xc1, 0x7b, 0x12, 0xad,
	0xc8, 0xf9, 0x21, 0xf0, 0x11, 0x60, 0xf7, 0x21, 0x42, 0xd8, 0x5e, 0x07, 0xd3, 0x0b, 0xb6, 0xff,
	0x6e, 0x3a, 0x88, 0x16, 0xaf, 0xb3, 0x42, 0x60, 0x69, 0x53, 0x96, 0xa9, 0x3a, 0xfc, 0x6c, 0x53,
	0x59, 0xdf, 0x2f, 0xc3, 0xa0, 0xe2, 0x89, 0x96, 0x42, 0x16, 0x41, 0xa1, 0x82, 0x37, 0x81, 0x61,
	0x93, 0xa6, 0x9e, 0x2b, 0xf8, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x97, 0x01, 0x27, 0xd6, 0xee,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MathServiceClient is the client API for MathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathServiceClient interface {
	Add(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error)
	Subtract(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error)
	Multiply(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error)
	Divide(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error)
	Palindrome(ctx context.Context, in *PalindromeRequest, opts ...grpc.CallOption) (*PalindromeResponse, error)
}

type mathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMathServiceClient(cc grpc.ClientConnInterface) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) Add(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error) {
	out := new(MathResponse)
	err := c.cc.Invoke(ctx, "/MathService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Subtract(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error) {
	out := new(MathResponse)
	err := c.cc.Invoke(ctx, "/MathService/Subtract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Multiply(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error) {
	out := new(MathResponse)
	err := c.cc.Invoke(ctx, "/MathService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Divide(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error) {
	out := new(MathResponse)
	err := c.cc.Invoke(ctx, "/MathService/Divide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Palindrome(ctx context.Context, in *PalindromeRequest, opts ...grpc.CallOption) (*PalindromeResponse, error) {
	out := new(PalindromeResponse)
	err := c.cc.Invoke(ctx, "/MathService/Palindrome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServiceServer is the server API for MathService service.
type MathServiceServer interface {
	Add(context.Context, *MathRequest) (*MathResponse, error)
	Subtract(context.Context, *MathRequest) (*MathResponse, error)
	Multiply(context.Context, *MathRequest) (*MathResponse, error)
	Divide(context.Context, *MathRequest) (*MathResponse, error)
	Palindrome(context.Context, *PalindromeRequest) (*PalindromeResponse, error)
}

// UnimplementedMathServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMathServiceServer struct {
}

func (*UnimplementedMathServiceServer) Add(ctx context.Context, req *MathRequest) (*MathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedMathServiceServer) Subtract(ctx context.Context, req *MathRequest) (*MathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subtract not implemented")
}
func (*UnimplementedMathServiceServer) Multiply(ctx context.Context, req *MathRequest) (*MathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (*UnimplementedMathServiceServer) Divide(ctx context.Context, req *MathRequest) (*MathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Divide not implemented")
}
func (*UnimplementedMathServiceServer) Palindrome(ctx context.Context, req *PalindromeRequest) (*PalindromeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Palindrome not implemented")
}

func RegisterMathServiceServer(s *grpc.Server, srv MathServiceServer) {
	s.RegisterService(&_MathService_serviceDesc, srv)
}

func _MathService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Add(ctx, req.(*MathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Subtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Subtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Subtract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Subtract(ctx, req.(*MathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Multiply(ctx, req.(*MathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Divide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Divide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Divide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Divide(ctx, req.(*MathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Palindrome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PalindromeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Palindrome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathService/Palindrome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Palindrome(ctx, req.(*PalindromeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MathService_Add_Handler,
		},
		{
			MethodName: "Subtract",
			Handler:    _MathService_Subtract_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _MathService_Multiply_Handler,
		},
		{
			MethodName: "Divide",
			Handler:    _MathService_Divide_Handler,
		},
		{
			MethodName: "Palindrome",
			Handler:    _MathService_Palindrome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}
